import {
  LayoutDashboard,
  ShoppingBag,
  UtensilsCrossed,
  ChefHat,
  Boxes,
  Users,
  CalendarClock,
  BarChart3,
  FileText,
  CreditCard,
  UserCircle2,
  Settings,
  Bell,
  HelpCircle,
  Sparkles,
} from "lucide-react";

export const navigation = [
  { id: "dashboard", label: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
  { id: "ai", label: "AI Assistant", href: "/ai", icon: Sparkles },
  { id: "orders", label: "Orders", href: "/orders", icon: ShoppingBag },
  { id: "tables", label: "Tables", href: "/tables", icon: UtensilsCrossed },
  { id: "kitchen", label: "Kitchen", href: "/kitchen", icon: ChefHat },
  { id: "inventory", label: "Inventory", href: "/inventory", icon: Boxes },
  { id: "customers", label: "Customers", href: "/customers", icon: Users },
  { id: "reservations", label: "Reservations", href: "/reservations", icon: CalendarClock },
  { id: "analytics", label: "Analytics", href: "/analytics", icon: BarChart3 },
  { id: "reports", label: "Reports", href: "/reports", icon: FileText },
  { id: "billing", label: "Billing", href: "/billing", icon: CreditCard },
  { id: "profile", label: "Profile", href: "/profile", icon: UserCircle2 },
  { id: "settings", label: "Settings", href: "/settings", icon: Settings },
  { id: "notifications", label: "Notifications", href: "/notifications", icon: Bell },
  { id: "help", label: "Help Center", href: "/help", icon: HelpCircle },
];
